export const ErrorCodes = {
  // Auth
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_REFRESH_INVALID: "AUTH_REFRESH_INVALID",
  AUTH_CREDENTIALS_INVALID: "AUTH_CREDENTIALS_INVALID",
  AUTH_ACCOUNT_DISABLED: "AUTH_ACCOUNT_DISABLED",
  AUTH_INSUFFICIENT_ROLE: "AUTH_INSUFFICIENT_ROLE",
  AUTH_CAMERA_ACCESS_DENIED: "AUTH_CAMERA_ACCESS_DENIED",
  AUTH_TENANT_MISMATCH: "AUTH_TENANT_MISMATCH",
  AUTH_EMAIL_TAKEN: "AUTH_EMAIL_TAKEN",

  // Camera
  CAMERA_NOT_FOUND: "CAMERA_NOT_FOUND",
  CAMERA_CONNECTION_FAILED: "CAMERA_CONNECTION_FAILED",
  CAMERA_AUTH_FAILED: "CAMERA_AUTH_FAILED",
  CAMERA_STREAM_TIMEOUT: "CAMERA_STREAM_TIMEOUT",
  CAMERA_CODEC_UNSUPPORTED: "CAMERA_CODEC_UNSUPPORTED",
  CAMERA_OFFLINE: "CAMERA_OFFLINE",
  CAMERA_ALREADY_EXISTS: "CAMERA_ALREADY_EXISTS",
  CAMERA_LIMIT_REACHED: "CAMERA_LIMIT_REACHED",
  CAMERA_DISCOVERY_TIMEOUT: "CAMERA_DISCOVERY_TIMEOUT",
  CAMERA_PTZ_UNSUPPORTED: "CAMERA_PTZ_UNSUPPORTED",

  // Video
  VIDEO_RECORDING_NOT_FOUND: "VIDEO_RECORDING_NOT_FOUND",
  VIDEO_RECORDING_IN_PROGRESS: "VIDEO_RECORDING_IN_PROGRESS",
  VIDEO_PLAYBACK_UNAVAILABLE: "VIDEO_PLAYBACK_UNAVAILABLE",
  VIDEO_TRANSCODE_FAILED: "VIDEO_TRANSCODE_FAILED",
  VIDEO_STORAGE_FULL: "VIDEO_STORAGE_FULL",
  VIDEO_UPLOAD_FAILED: "VIDEO_UPLOAD_FAILED",

  // Rules
  RULE_NOT_FOUND: "RULE_NOT_FOUND",
  RULE_INVALID_CONDITION: "RULE_INVALID_CONDITION",
  RULE_INVALID_ACTION: "RULE_INVALID_ACTION",
  RULE_LIMIT_REACHED: "RULE_LIMIT_REACHED",

  // Extensions
  EXT_NOT_FOUND: "EXT_NOT_FOUND",
  EXT_NOT_INSTALLED: "EXT_NOT_INSTALLED",
  EXT_ALREADY_INSTALLED: "EXT_ALREADY_INSTALLED",
  EXT_INSTALL_FAILED: "EXT_INSTALL_FAILED",
  EXT_RATE_LIMITED: "EXT_RATE_LIMITED",
  EXT_EXECUTION_TIMEOUT: "EXT_EXECUTION_TIMEOUT",
  EXT_EXECUTION_ERROR: "EXT_EXECUTION_ERROR",
  EXT_LIMIT_REACHED: "EXT_LIMIT_REACHED",

  // Tenant
  TENANT_NOT_FOUND: "TENANT_NOT_FOUND",
  TENANT_PLAN_LIMIT: "TENANT_PLAN_LIMIT",
  TENANT_USER_LIMIT_REACHED: "TENANT_USER_LIMIT_REACHED",

  // General
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
