api:
  listen: ":1984"

rtsp:
  listen: ":8554"

webrtc:
  listen: ":8555"
  candidates:
    - stun:stun.l.google.com:19302

log:
  level: info

streams:
  demo-cam-1:
    - ffmpeg:testsrc=size=1280x720:rate=15#video=h264
  demo-cam-2:
    - ffmpeg:testsrc2=size=1920x1080:rate=25#video=h264
  248c5f1d-ac05-447a-8543-9db0942482b1:
    - rtsp://192.168.4.20:8554/stream
