// Package proto contains hand-written Go types matching the gRPC protobuf definitions.
// In production, these would be generated by protoc-gen-go and protoc-gen-go-grpc.
// This file provides the types needed for compilation without running protoc.
package proto

import (
	"context"

	"google.golang.org/grpc"
)

// ---------- Request / Response types ----------

type StartRecordingRequest struct {
	CameraId    string  `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	TenantId    string  `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Trigger     string  `protobuf:"bytes,3,opt,name=trigger,proto3" json:"trigger,omitempty"`
	DurationSec int32   `protobuf:"varint,4,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
}

type StartRecordingResponse struct {
	Success     bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RecordingId string `protobuf:"bytes,2,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	Message     string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

type StopRecordingRequest struct {
	RecordingId string `protobuf:"bytes,1,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
}

type StopRecordingResponse struct {
	Success     bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DurationSec int32  `protobuf:"varint,2,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	Message     string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

type GetRecordingStatusRequest struct {
	RecordingId string `protobuf:"bytes,1,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
}

type RecordingStatusResponse struct {
	RecordingId string `protobuf:"bytes,1,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	Status      string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	DurationSec int32  `protobuf:"varint,3,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	SizeBytes   int64  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	StartTime   string `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime     string `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

type GenerateSnapshotRequest struct {
	CameraId     string  `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	TenantId     string  `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RecordingId  string  `protobuf:"bytes,3,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	TimestampSec float32 `protobuf:"fixed32,4,opt,name=timestamp_sec,json=timestampSec,proto3" json:"timestamp_sec,omitempty"`
}

type GenerateSnapshotResponse struct {
	Success     bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SnapshotId  string `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	StoragePath string `protobuf:"bytes,3,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	Message     string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

type GetPlaybackURLRequest struct {
	RecordingId string `protobuf:"bytes,1,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	TenantId    string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
}

type PlaybackURLResponse struct {
	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PlaybackUrl  string `protobuf:"bytes,2,opt,name=playback_url,json=playbackUrl,proto3" json:"playback_url,omitempty"`
	ExpiresInSec int32  `protobuf:"varint,3,opt,name=expires_in_sec,json=expiresInSec,proto3" json:"expires_in_sec,omitempty"`
	Message      string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

// ---------- Service interface and registration ----------

// VideoPipelineServiceServer is the server API for VideoPipelineService.
type VideoPipelineServiceServer interface {
	StartRecording(context.Context, *StartRecordingRequest) (*StartRecordingResponse, error)
	StopRecording(context.Context, *StopRecordingRequest) (*StopRecordingResponse, error)
	GetRecordingStatus(context.Context, *GetRecordingStatusRequest) (*RecordingStatusResponse, error)
	GenerateSnapshot(context.Context, *GenerateSnapshotRequest) (*GenerateSnapshotResponse, error)
	GetPlaybackURL(context.Context, *GetPlaybackURLRequest) (*PlaybackURLResponse, error)
}

// UnimplementedVideoPipelineServiceServer provides default unimplemented methods.
type UnimplementedVideoPipelineServiceServer struct{}

func (UnimplementedVideoPipelineServiceServer) StartRecording(context.Context, *StartRecordingRequest) (*StartRecordingResponse, error) {
	return nil, grpc.Errorf(12, "method StartRecording not implemented") //nolint:staticcheck
}
func (UnimplementedVideoPipelineServiceServer) StopRecording(context.Context, *StopRecordingRequest) (*StopRecordingResponse, error) {
	return nil, grpc.Errorf(12, "method StopRecording not implemented") //nolint:staticcheck
}
func (UnimplementedVideoPipelineServiceServer) GetRecordingStatus(context.Context, *GetRecordingStatusRequest) (*RecordingStatusResponse, error) {
	return nil, grpc.Errorf(12, "method GetRecordingStatus not implemented") //nolint:staticcheck
}
func (UnimplementedVideoPipelineServiceServer) GenerateSnapshot(context.Context, *GenerateSnapshotRequest) (*GenerateSnapshotResponse, error) {
	return nil, grpc.Errorf(12, "method GenerateSnapshot not implemented") //nolint:staticcheck
}
func (UnimplementedVideoPipelineServiceServer) GetPlaybackURL(context.Context, *GetPlaybackURLRequest) (*PlaybackURLResponse, error) {
	return nil, grpc.Errorf(12, "method GetPlaybackURL not implemented") //nolint:staticcheck
}

// UnsafeVideoPipelineServiceServer may be embedded to opt out of forward compatibility.
type UnsafeVideoPipelineServiceServer interface {
	mustEmbedUnimplementedVideoPipelineServiceServer()
}

// RegisterVideoPipelineServiceServer registers the service handler with the gRPC server.
func RegisterVideoPipelineServiceServer(s *grpc.Server, srv VideoPipelineServiceServer) {
	s.RegisterService(&VideoPipelineService_ServiceDesc, srv)
}

// VideoPipelineService_ServiceDesc is the grpc.ServiceDesc for VideoPipelineService.
var VideoPipelineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osp.videopipeline.v1.VideoPipelineService",
	HandlerType: (*VideoPipelineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRecording",
			Handler:    _VideoPipelineService_StartRecording_Handler,
		},
		{
			MethodName: "StopRecording",
			Handler:    _VideoPipelineService_StopRecording_Handler,
		},
		{
			MethodName: "GetRecordingStatus",
			Handler:    _VideoPipelineService_GetRecordingStatus_Handler,
		},
		{
			MethodName: "GenerateSnapshot",
			Handler:    _VideoPipelineService_GenerateSnapshot_Handler,
		},
		{
			MethodName: "GetPlaybackURL",
			Handler:    _VideoPipelineService_GetPlaybackURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/video_pipeline.proto",
}

func _VideoPipelineService_StartRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoPipelineServiceServer).StartRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/osp.videopipeline.v1.VideoPipelineService/StartRecording"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoPipelineServiceServer).StartRecording(ctx, req.(*StartRecordingRequest))
	})
}

func _VideoPipelineService_StopRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoPipelineServiceServer).StopRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/osp.videopipeline.v1.VideoPipelineService/StopRecording"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoPipelineServiceServer).StopRecording(ctx, req.(*StopRecordingRequest))
	})
}

func _VideoPipelineService_GetRecordingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordingStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoPipelineServiceServer).GetRecordingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/osp.videopipeline.v1.VideoPipelineService/GetRecordingStatus"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoPipelineServiceServer).GetRecordingStatus(ctx, req.(*GetRecordingStatusRequest))
	})
}

func _VideoPipelineService_GenerateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoPipelineServiceServer).GenerateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/osp.videopipeline.v1.VideoPipelineService/GenerateSnapshot"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoPipelineServiceServer).GenerateSnapshot(ctx, req.(*GenerateSnapshotRequest))
	})
}

func _VideoPipelineService_GetPlaybackURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaybackURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoPipelineServiceServer).GetPlaybackURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/osp.videopipeline.v1.VideoPipelineService/GetPlaybackURL"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoPipelineServiceServer).GetPlaybackURL(ctx, req.(*GetPlaybackURLRequest))
	})
}
